import Head from 'next/head'
import { PropsWithChildren } from "react";
import Link from 'next/link';


export interface Props {
    title?: string
}

export const Layout = ({ title, children }: PropsWithChildren<Props> ) => {
    return (
        <>
        <Head>
        <title>{`${title ? `${title} · ` : ''} My Job board`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css"></link>
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <nav>
                <Link href="/">Home </Link> · <Link href="/about">About</Link>
            </nav>
            <h1>My Job Board</h1>
        </header>
        <main>{children}</main>
        </>
    )
}

export default Layout;

